# 학생 이동 및 교환 비용 행렬 계산

In [6]:
import pandas as pd
df = pd.read_excel("최종_그룹_배정_결과.xlsx", sheet_name="신규반번호순")
df.head()

학교명  학년반번호  성별   이름  기초학습역량_언어_T점수 기초학습역량_언어_수준  기초학습역량_논리수학_T점수  \
0  장대중학교  10516   1  권원준             23           부족               23   
1  장대중학교  10505   2  김서윤             32        매우 낮음               31   
2  장대중학교  10203   2  김소희             81          최우수               86   
3  장대중학교  10605   2  김예은             81          최우수               86   
4  장대중학교  10615   1   김완             32        매우 낮음               31   

  기초학습역량_논리수학_수준  기초학습역량_공간_T점수 기초학습역량_공간_수준  ...  정서적 민감성_우울_T점수  \
0             부족             45           낮음  ...              45   
1          매우 낮음             26           부족  ...              33   
2            최우수             76          최우수  ...              33   
3            최우수             76          최우수  ...              33   
4          매우 낮음             26           부족  ...              33   

   정서적 민감성_우울_수준  정서적 민감성_부정적 \n대인정서_T점수  정서적 민감성_부정적 \n대인정서_수준  \
0             보통                      48                     보통   
1             낮음                      36                     낮음   
2             낮음                      36                     낮음   
3             낮음                      36                     낮음   
4             낮음                      36                     낮음   

  정서적 민감성_예민성_T점수  정서적 민감성_예민성_수준 정서적 민감성_과잉행동_T점수  정서적 민감성_과잉행동_수준 신규반  번호  
0              32              낮음               62               높음   1   1  
1              32              낮음               36               낮음   1   2  
2              32              낮음               36               낮음   1   3  
3              32              낮음               36               낮음   1   4  
4              32              낮음               36               낮음   1   5  

[5 rows x 27 columns]

In [15]:
import numpy as np
source_group_df = df[df['신규반']==1].copy()
s_idx = source_group_df.index.values
print(s_idx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28]


In [16]:
match_group_idx = [2,3,4,5,6,7,8,9,10]
t_idx = np.array(match_group_idx)
print(t_idx)

[ 2  3  4  5  6  7  8  9 10]


In [17]:
s, t = np.meshgrid(s_idx, t_idx, indexing='ij') # 인덱스 행렬화 / s : 출발 학생 인덱스, t : 도착 그룹 인덱스
print(s)

[[ 0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5]
 [ 6  6  6  6  6  6  6  6  6]
 [ 7  7  7  7  7  7  7  7  7]
 [ 8  8  8  8  8  8  8  8  8]
 [ 9  9  9  9  9  9  9  9  9]
 [10 10 10 10 10 10 10 10 10]
 [11 11 11 11 11 11 11 11 11]
 [12 12 12 12 12 12 12 12 12]
 [13 13 13 13 13 13 13 13 13]
 [14 14 14 14 14 14 14 14 14]
 [15 15 15 15 15 15 15 15 15]
 [16 16 16 16 16 16 16 16 16]
 [17 17 17 17 17 17 17 17 17]
 [18 18 18 18 18 18 18 18 18]
 [19 19 19 19 19 19 19 19 19]
 [20 20 20 20 20 20 20 20 20]
 [21 21 21 21 21 21 21 21 21]
 [22 22 22 22 22 22 22 22 22]
 [23 23 23 23 23 23 23 23 23]
 [24 24 24 24 24 24 24 24 24]
 [25 25 25 25 25 25 25 25 25]
 [26 26 26 26 26 26 26 26 26]
 [27 27 27 27 27 27 27 27 27]
 [28 28 28 28 28 28 28 28 28]]


In [ ]:
# 외향성_사회적 친밀성_T점수
scores = df.loc[:, '외향성_사회적 친밀성_T점수'].values
print(scores)

[37 37 37 37 37 37 37 85 85 85 37 37 37 37 37 85 37 37 37 85 37 37 37 37
 85 37 85 85 37 37 37 37 37 85 37 85 37 37 37 85 37 37 37 85 37 37 37 85
 37 37 85 37 37 85 37 37 37 85 37 85 37 37 85 37 37 37 85 37 37 37 37 37
 37 85 37 37 85 37 85 37 37 37 85 37 37 37 85 37 37 37 37 37 37 85 37 85
 37 37 37 37 37 37 85 85 37 37 37 85 37 37 37 85 85 37 37 37 85 37 37 85
 37 37 37 37 85 85 37 37 37 37 37 85 37 37 37 37 37 85 37 37 85 37 37 37
 37 37 37 85 37 37 37 37 37 37 85 37 37 37 37 85 37 37 85 37 85 37 37 37
 37 37 85 37 37 85 37 37 37 85 37 37 37 85 37 37 37 85 37 37 85 37 37 37
 85 37 85 37 37 37 37 37 85 37 37 37 37 37 85 37 85 37 85 37 85 37 37 37
 37 37 37 37 37 85 37 37 37 37 37 37 85 85 37 37 37 37 85 37 37 37 37 37
 37 85 37 37 85 37 37 37 85 37 37 37 37 85 85 37 37 85 37 37 37 37 37 37
 85 85 37 37 37 37 37 37 85 37 37 85 37 85 37 37 37 37 85 37 37 37 37 85
 37 37 37 37 37]


293